### ISSUE TITLE
problems with new raspian stretch network interface configuration - batman adv

### ISSUE THREAD

**Issue by suiluj** [amroczeK/tribes-mesh-network#2]
Hello amroczeK,

i tried your guide for batman adv.

Unfortunately it was not possible because of the network commands for raspberrypi stretch in the latest versions.
Do you have a solution?

Here is an example:

```
sudo ifconfig wlan0 mtu 1532
SIOCSIFMTU: Invalid argument
```

**Comment by amroczeK** [comment]
Hi this project was done using the Raspberry Jessie Lite OS. Please read the new documentation to find the equivalent commands.

**Comment by suiluj** [comment]
I just found out that `sudo ifconfig wlan0 mtu 1500` is limited too 1500 and lower values.
(with values less than 1500 the command works)

Also i was not able to set the interface to adhoc mode (which is ibss with iw):

```
pi@rpizero1:~ $ sudo iw dev wlan0 set type ibss
command failed: Device or resource busy (-16)
pi@rpizero1:~ $ sudo iw dev wlan0 interface add adh0 type ibss
command failed: Device or resource busy (-16)
```

Does someone has a solution for this error? i tried disabling wpa_supplicant and dhcpcd but it did not work either.

I am using a Raspberry Pi Zero W(H)

**Comment by amroczeK** [comment]
I asked someone else you used my repository for their project and using raspberry stretch.

He said you should try disabling the DHCPCD service on boot as it uses the wireless interface to source an IP. In the script just simply add a command to disable the service to free the interface.

**Comment by suiluj** [comment]
thanks for your help.
i still was not able to set the mtu too higher values but a few days ago i was able to create the network and wrote a small tutorial, too (including your reference 👍 )

i just added `denyinterfaces wlan0` at the end of `/etc/dhcpcd.conf` so i can still use dhcpcd for other interfaces.

here is a link to my tutorial repo (still adding stuff but it is working so far  including gateways for internet):

[github/suiluj/pi-adhoc-mqtt-cluster](https://github.com/suiluj/pi-adhoc-mqtt-cluster)

**Comment by amroczeK** [comment]
Well done!

I will link provide a link to your git for anyone using stretch.
